Update update_content.yaml

diff --git a/.github/workflows/update_content.yaml b/.github/workflows/update_content.yaml
--- a/.github/workflows/update_content.yaml
+++ b/.github/workflows/update_content.yaml
@@ -40,11 +40,11 @@ jobs:
         else
           echo "No updates in content."
           echo "has_updates=false" >> $GITHUB_OUTPUT
-          exit 1  # Fail the step (and job) when there are no updates
+          # exit 1  # Fail the step (and job) when there are no updates
         fi
 
     - name: Push changes
       if: steps.update_submodule.outputs.has_updates == 'true'
       uses: ad-m/github-push-action@v0.8.0
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
